name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main  # Here source code branch is `master`, it could be other branch

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build with Jekyll

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3"
          bundler-cache: true
          working-directory: ./src

      - name: Build
        run: bundle exec jekyll build --trace
        working-directory: ./src

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./src/_site"

  deploy:
    name: Deploy to GitHub pages

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
